version: 2

models:
  - name: affiliate_ad
    description: "Final ads data"
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('staging_impact_ads')
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - id
            - network_key_id
            - namespace
    columns:
      - name: id
        description: "Ad id"
        tests:
          - not_null
          - unique
      - name: network_key_id
        description: "Id of account this record belongs to"
        tests:
          - not_null
      - name: namespace
        description: "Namespace (agency) this record belongs to"
        tests:
          - not_null
      - name: type
        description: "Ad type"
        tests:
          - not_null
          - accepted_values:
              severity: warn
              values:
                [
                  "banner",
                  "button_1",
                  "button_2",
                  "coupon",
                  "custom",
                  "field_banner",
                  "full_banner",
                  "half_banner",
                  "half_page_ad",
                  "large_rectangle",
                  "leaderboard",
                  "medium_rectangle",
                  "micro_banner",
                  "n/a",
                  "promo code",
                  "rectangle",
                  "rectangle_3_1_",
                  "skyscraper",
                  "square_button",
                  "square_pop_up",
                  "text_link",
                  "vertical_banner",
                  "vertical_rectangle",
                  "wide_skyscraper",
                ]
