version: 2

models:
  - name: staging_impact_ads
    description: "Staging Impact ads data"
    columns:
      - name: id
        description: "Ad id"
        tests:
          - not_null
          - unique
      - name: data_source
        description: "The path of the file where data is originated from"
        tests:
          - not_null
      - name: type
        description: "Ad type"
        tests:
          - not_null
          - accepted_values:
              severity: warn
              values: [
                "banner",
                "button_1",
                "button_2",
                "coupon",
                "custom",
                "field_banner",
                "full_banner",
                "half_banner",
                "half_page_ad",
                "large_rectangle",
                "leaderboard",
                "medium_rectangle",
                "micro_banner",
                "n/a",
                "promo code",
                "rectangle",
                "rectangle_3_1_",
                "skyscraper",
                "square_button",
                "square_pop_up",
                "text_link",
                "vertical_banner",
                "vertical_rectangle",
                "wide_skyscraper"
              ]
  - name: staging_impact_clicks
    description: "Staging Impact clicks data"
    columns:
      - name: commissionId
        description: "Unique identifier of a click record"
        tests:
          - not_null
          - unique
      - name: deviceType
        description: "Type of the device"
        tests:
          - dbt_utils.not_constant
      - name: clickCount
        description: "Click count"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
      - name: eventDate
        tests:
          - dbt_utils.accepted_range:
              max_value: "getdate()"
