{{
  config(
    materialized='table'
  )
}}

SELECT t.value:AdCodeTemplate::VARCHAR AS AdCodeTemplate,
        CASE
            WHEN t.value:AdType::VARCHAR IS NULL THEN NULL
            WHEN LOWER(t.value:AdType::VARCHAR) = 'not_applicable' then 'n/a'
            ELSE LOWER(t.value:AdType::VARCHAR)
        END AS AdType,
        t.value:AllowDeepLinking::BOOLEAN AS AllowDeepLinking,
        t.value:BannerAlternativeTag::VARCHAR AS BannerAlternativeTag,
        t.value:BogoBuyImageUrl::VARCHAR AS BogoBuyImageUrl,
        t.value:BogoBuyName::VARCHAR AS BogoBuyName,
        t.value:BogoBuyQuantity::VARCHAR AS BogoBuyQuantity,
        t.value:BogoBuyScope::VARCHAR AS BogoBuyScope,
        t.value:BogoGetDiscountAmount::VARCHAR AS BogoGetDiscountAmount,
        t.value:BogoGetDiscountCurrency::VARCHAR AS BogoGetDiscountCurrency,
        t.value:BogoGetDiscountPercent::VARCHAR AS BogoGetDiscountPercent,
        t.value:BogoGetDiscountType::VARCHAR AS BogoGetDiscountType,
        t.value:BogoGetImageUrl::VARCHAR AS BogoGetImageUrl,
        t.value:BogoGetName::VARCHAR AS BogoGetName,
        t.value:BogoGetQuantity::VARCHAR AS BogoGetQuantity,
        t.value:BogoGetScope::VARCHAR AS BogoGetScope,
        t.value:CampaignId::VARCHAR AS CampaignId,
        t.value:CampaignName::VARCHAR AS CampaignName,
        t.value:CouponAllowCustomPromoCode::VARCHAR AS CouponAllowCustomPromoCode,
        t.value:CouponLinkName::VARCHAR AS CouponLinkName,
        t.value:CustomAdServingUrl::VARCHAR AS CustomAdServingUrl,
        t.value:CustomisationCharge::NUMBER AS CustomisationCharge,
        t.value:DealCategories::VARCHAR AS DealCategories,
        t.value:DealDefaultPromoCode::VARCHAR AS DealDefaultPromoCode,
        t.value:DealDescription::VARCHAR AS DealDescription,
        t.value:DealEndDate::VARCHAR AS DealEndDate,
        t.value:DealId::VARCHAR AS DealId,
        t.value:DealName::VARCHAR AS DealName,
        t.value:DealProducts::VARIANT AS DealProducts,
        t.value:DealRestrictedMediaPartnerGroups::VARIANT AS DealRestrictedMediaPartnerGroups,
        t.value:DealRestrictedMediaPartners::VARIANT AS DealRestrictedMediaPartners,
        t.value:DealScope::VARIANT AS DealScope,
        t.value:DealStartDate::VARCHAR AS DealStartDate,
        t.value:DealState::VARCHAR AS DealState,
        t.value:DealType::VARCHAR AS DealType,
        t.value:Description::VARCHAR AS Description,
        t.value:DiscountAmount::VARCHAR AS DiscountAmount,
        t.value:DiscountCurrency::VARCHAR AS DiscountCurrency,
        t.value:DiscountMaximumPercent::VARCHAR AS DiscountMaximumPercent,
        t.value:DiscountPercent::VARCHAR AS DiscountPercent,
        t.value:DiscountPercentRangeEnd::VARCHAR AS DiscountPercentRangeEnd,
        t.value:DiscountPercentRangeStart::VARCHAR AS DiscountPercentRangeStart,
        t.value:DiscountType::VARCHAR AS DiscountType,
        t.value:GetHtmlCodeType::VARCHAR AS GetHtmlCodeType,
        t.value:Gift::VARCHAR AS Gift,
        t.value:IabAdUnit::VARCHAR AS IabAdUnit,
        t.value:Id::NUMBER AS Id,
        t.value:Labels::VARCHAR AS Labels,
        t.value:LandingPage::VARCHAR AS LandingPage,
        t.value:Language::VARCHAR AS Language,
        t.value:LimitedTimeEndDate::VARCHAR AS LimitedTimeEndDate,
        t.value:LimitedTimeStartDate::DATETIME AS LimitedTimeStartDate,
        t.value:LinkText::VARCHAR AS LinkText,
        t.value:MaximumSavingsAmount::VARCHAR AS MaximumSavingsAmount,
        t.value:MaximumSavingsCurrency::VARCHAR AS MaximumSavingsCurrency,
        t.value:MinimumPurchaseAmount::VARCHAR AS MinimumPurchaseAmount,
        t.value:MinimumPurchaseAmountCurrency::VARCHAR AS MinimumPurchaseAmountCurrency,
        t.value:MobileFallbacks::VARIANT AS MobileFallbacks,
        t.value:MobileReady::BOOLEAN AS MobileReady,
        t.value:Name::VARCHAR AS Name,
        t.value:PhoneTracking::BOOLEAN AS PhoneTracking,
        t.value:PromoCodeTracking::BOOLEAN AS PromoCodeTracking,
        t.value:PurchaseLimitQuantity::VARCHAR AS PurchaseLimitQuantity,
        t.value:RebateAmount::VARCHAR AS RebateAmount,
        t.value:RebateCurrency::VARCHAR AS RebateCurrency,
        t.value:RestrictedMediaPartnerGroups::VARIANT AS RestrictedMediaPartnerGroups,
        t.value:RestrictedMediaPartners::VARIANT AS RestrictedMediaPartners,
        t.value:Season::VARCHAR AS Season,
        t.value:SynchAdsPromoCodes::VARCHAR AS SynchAdsPromoCodes,
        NULLIF(t.value:ThirdPartyServableAdCreativeHeight, '')::INTEGER AS ThirdPartyServableAdCreativeHeight,
        NULLIF(t.value:ThirdPartyServableAdCreativeWidth, '')::INTEGER AS ThirdPartyServableAdCreativeWidth,
        t.value:TopSeller::BOOLEAN AS TopSeller,
        t.value:Uri::VARCHAR AS Uri,
        S.data_source AS data_source
  FROM {{ ref('raw_impact_ads') }} AS S
          , TABLE(flatten(S.$1,'Ads')) t
