version: 2

models:
  - name: affiliate_sku
    description: "Final skus data"
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('staging_impact_skus')
    columns:
      - name: affluent_id
        description: "Unique record identifier"
        tests:
          - not_null
          - unique
      - name: network_key_id
        description: "Id of account this record belongs to"
        tests:
          - not_null
      - name: namespace
        description: "Namespace (agency) this record belongs to"
        tests:
          - not_null
